version: '3'

volumes:  
  postgres_data: {} 

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: docker 
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 6003:5432
  app:
    build: 
      context: .      
      dockerfile: ./docker/app/Dockerfile 
    depends_on:
      - db
  nginx_server:
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    depends_on:      
      - app    
    ports:      
      - 80:80