version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: docker 
      POSTGRES_PASSWORD: docker
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 6002:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rake db:migrate && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/codecurious
    ports:
      - 3000:3000
    depends_on:
      - db